Upgraded to Python3 using the 2to3 tool shipped with python 3
After 3 executions of 2to3-tool still some errors:
RefactoringTool: Can't parse .\options.py: ParseError: bad input:
type=22, value='=', context=('', (119, 23))
RefactoringTool: Can't parse .\medusa\monitor.py: ParseError: bad input:
type=22, value='=', context=('', (321, 37))
RefactoringTool: Can't parse .\medusa\monitor_client_win32.py:
ParseError: bad input: type=22, value='=', context=('', (45, 33))

And there was a warning that I manually fixed in code:
RefactoringTool: ### In file .\medusa\xmlrpc_handler.py ###
RefactoringTool: Line 59: could not convert: raise "NotYetImplemented"
RefactoringTool: Python 3 does not support string exceptions